### ISSUE TITLE
get_expected function fails

### ISSUE THREAD

**Issue by NateMietk** [NateMietk/human-ignitions-wui#1]
https://github.com/NateMietk/human-ignitions-wui/blob/23b917b6a106d89121df479e9e1e41a62d7c03ef/src/R/analysis/11_observed_versus_expected.R#L2-L45

Hey @mbjoseph

I have an issue that I have been grappling with off and on for a bit now. I am having issues iterating the `get_expected` function I built and was hoping you could help me fix the last part.  It is pretty straight forward.  I am trying to develop observed versus expected values to test differences between wildfire ignition and wui/wildland areas. The resultant output should be a large dataframe that has the raw observed and the expected data for all variables so that I can run Chi-Square tests and compute the percent expected differences.  I have it running when it is one-off but I cannot iterate across my variables.  The function seems to be failing during `spread` when I am cleaning the dataframe prior to the for loop (line20).  I have a feeling it is because I do not understand how to deal with the `split` dataframe prior to executing the function.  Any advice would be appreciated. Thanks!

**Comment by mbjoseph** [comment]
Hi @NateMietk - can you give me the steps needed to reproduce the error? 

I assumed I need to run the previous 10 scripts, but I am not able to run the first script `src/R/1_create_folders.R` because there are some objects referenced that are not created (e.g., `conus_crt`).

**Comment by NateMietk** [comment]
@mbjoseph you should just need to run the `11_observed_versus_expected.R` code which has the code I pulled the issue.  I created it as a stand alone so it would be easier to debug. Thanks!

**Comment by mbjoseph** [comment]
Ok - think you just need to use `map()`, but let me know if #2 doesn't solve the problem.

**Comment by NateMietk** [comment]
Hey @mbjoseph that does it! I was trying to use `map()` but did not realize that I needed the `~`.  Thanks for the help!
